services:
  server:
    build: ./server
    image: url-checker-server
    container_name: url-checker-server
    ports:
      - '3001:3001'
    environment:
      PORT: '3001'
    restart: unless-stopped

  client:
    build: ./client
    image: url-checker-client
    container_name: url-checker-client
    ports:
      - '3000:3000'
    depends_on:
      - server
    restart: unless-stopped
